version: "3.8"
name: "telemedicine"

services:
  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/symfony
    depends_on:
      - php


  php:
    build: .
    container_name: php
    environment:
      SYMFONY_ENV: prod
    entrypoint: ['/var/www/symfony/entrypoint.sh']
    depends_on:
      db:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 3G

  db:
    image: postgres:14
    restart: always
    shm_size: 128mb
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
volumes:
  db: