name: TEST
on:
  push:

jobs:
  test: 
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: symfony_test
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U symfnoy -d symfnoy_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup PHP
      uses: shivammathur/setup-php@2.32.0
      with:
         php-version: "8.1"
         tools: composer
         coverage: none
         
    - name: Copy .env.example to .env
      run: cp .exapmle.env .env

         
    - name: Setup Environment variables
      run: |
        cat <<EOF > .env.test
          APP_ENV=dev
          APP_SECRET=30105fdbbfea30c5a09dfd3a095d5a23
          EOF
        cat <<EOF > .env.test
          KERNEL_CLASS='App\Kernel'
          APP_SECRET='$ecretf0rt3st'
          SYMFONY_DEPRECATIONS_HELPER=999999
          PANTHER_APP_ENV=panther
          PANTHER_ERROR_SCREENSHOT_DIR=./var/error-screenshots
          DATABASE_URL=postgresql://symfony:symfony@localhost:5432/symfony?serverVersion=14
          EOF

    - name: Install dependincies
      run: composer install --no-progress --prefer-dist --optimize-autoloader


    - name: Create database schema
      run: |
        php bin/console doctrine:database:create --if-not-exists --env=test
        php bin/console doctrine:schema:create --env=test
    - name: Run test
      run: |
        php bin/phpunit --testdox
      
