name: TEST
on:
  push:

jobs:
  test: 
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: symfony_test
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U symfnoy -d symfnoy_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup PHP
      uses: shivammathur/setup-php@2.32.0
      with:
         php-version: "8.1"
         tools: composer
         coverage: none

         
    - name: Setup Environment variables
      run: |
          echo -e "APP_ENV=dev\nAPP_SECRET=30105fdbbfea30c5a09dfd3a095d5a23\nDATABASE_URL=postgresql://symfony:symfony@localhost:5432/symfony?serverVersion=14" > .env
          echo -e "KERNEL_CLASS='App\Kernel'\nAPP_SECRET='\$ecretf0rt3st'\nSYMFONY_DEPRECATIONS_HELPER=999999\nPANTHER_APP_ENV=panther\nPANTHER_ERROR_SCREENSHOT_DIR=./var/error-screenshots\nDATABASE_URL=postgresql://symfony:symfony@localhost:5432/symfony?serverVersion=14" > .env.test
          
    - name: Install dependincies
      run: composer install --no-progress --prefer-dist --optimize-autoloader


    - name: Create database schema
      run: |
        php bin/console doctrine:database:create --if-not-exists --env=test --no-interaction
        php bin/console doctrine:schema:create --env=test --no-interaction
    
    - name: Load Fixtures
      run: |
        php bin/console doctrine:fixtures:load --env=test --no-interaction

    - name: Run test
      run: |
        php bin/phpunit

    - name: Send Telegram Notify on succes
      if: success()
      run: |
        curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "✅ Tests passed successfully!", "parse_mode": "HTML"}' \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
    - name: Send Telegram Notify on failure
      if: failure()
      run: |
        curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "❌ Tests failed! Check the logs.", "parse_mode": "HTML"}' \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
            
      
